### ISSUE TITLE
Can't generate class Diagram via drag .java into the .cld

### ISSUE THREAD

**Issue by IntHelloWorld** [takezoe/amateras-modeler#16] opened 2021-03-18 04:12 UTC
My eclipse version is 2020-09 (4.17.0) and my java version is Java 11.08.

**Comment by fuhailong1998** [comment] 2021-09-18 03:17
me2.

**Comment by takezoe** [comment] 2021-09-20 14:21
I couldn't reproduce this issue. Could you give me more information?

<img width="753" alt="Screen Shot 2021-09-20 at 23 20 38" src="https://user-images.githubusercontent.com/1094760/134018661-31b3ee74-02fc-4b39-afc3-03971def59f1.png">

**Comment by fuhailong1998** [comment] 2021-09-20 17:37
What did you do to generate it？Maybe i don't know how to use it.

**Comment by takezoe** [comment] 2021-09-21 03:14
So, what did your mean in your previous comment?

**Comment by creyesl** [comment] 2023-10-08 12:59
Hello, I am new to using eclipse and java, but I report the same problem, I am using Eclipse IDE Version 2023-09(4.29.0) and when I drag a class to the cld file, instead of inserting the class in it, it opens the file to edit it.
Use this path to install the plugin: https://takezoe.github.io/amateras-update-site/
and add this line to the end of my eclipse.ini file:
--add-opens=java.desktop/java.beans=ALL-UNNAMED

could you help me? I'm missing something?

**Comment by Sre803** [comment] 2024-03-29 02:23
After taking the steps to correctly install and use Amateras on Eclipse 2024 (Adding that one line at the end of the ini file), when i open a new cld file and drag the class onto the diagram, Eclipse interprets it as if i want to open the class to edit the code. The diagram editor is unresponsive when I detach the window and try to drag the class onto it. Furthermore I cant even edit the methods nor variables of a class created within the Diagram (only able to change the title). Hope this issue gets looked into, thanks in advance.

**Comment by takezoe** [comment] 2024-06-29 14:07
Released 2.2.0 which supports the latest version of Eclipse. Could you try it?

**Comment by takezoe** [comment] 2024-06-29 14:12
I would close this issue but feel free to reopen if you still see the same issue.

**Closed by takezoe** 2024-06-29 14:12 UTC
