### ISSUE TITLE
Last known Eclipse/JDK version with which AmaterasUML works?

### ISSUE THREAD

**Issue by megid2** [takezoe/amateras-modeler#12] opened 2020-10-12 18:14 UTC
Hi Naoki, could you tell us which Eclipse/JDK version combination you use to run AmaterasUML (or modeler)?

I am asking because Eclipse 2020-06 (PDE variant) and OpenJDK 11, with AmaterasModeler 1.1.0 via update site, gives a:
com.thoughtworks.xstream.mapper.CannotResolveClassException: net.java.amateras.uml.classdiagram.model.Visibility-1

Not expecting you to fix that any time soon, just knowing which version to take would be nice.

**Comment by takezoe** [comment] 2020-10-14 15:33
I can't remember which Eclipse version I've tested last time. However, Amateras ERD and UML are included in the latest version of [Pleiades](https://mergedoc.osdn.jp/) which is an Eclipse distribution with Japanese translated UI and various plugins. Since the latest version of Pleiades is based on Eclipse 2020-06, Amateras ERD and UML should work with this version Eclipse.

**Comment by megid2** [comment] 2020-10-14 15:49
Thanks for the answer Naoki. By "running" I mean "loading CLD files created with the same version", which is the minimum functionality for me. Since I wasnt sure whether you had the time to answer, I brute-forced my way through some Eclipse/Java versions today.

Using class diagrams (cld) and Eclipse PDE ("for Eclipse committers") variant:
eclipse 2019-03 works with JDK8, but not with JDK11
eclipse 2020-03 works with JDK8, but not with JDK11
eclipse 2020-06 works with JDK8, but not with JDK11

Old CLD files are rejected, but the exception differs.

For some reason, it was neccessary to use http instead of https (insecure!) to avoid an exception during plugin install.
http://takezoe.github.io/amateras-update-site

**Comment by megid2** [comment] 2020-10-14 15:50
Regarding migration of old CLD files: I made a lot of CLD files with AmaterasUML 1.3.2 ages ago, and would like the migrate them to the newer format. What do I have to do for this?

**Comment by takezoe** [comment] 2020-10-17 01:44
Hmm... It looks like an XStream's issue occurs depending on Java version. Fortunately, since CLD files are normal XML files, we can convert them for newer version by writing some XML processing code or simply modifying some lines by text editor (Actually, I did similar conversion before to migrate old files). However, to do that, we need to what is changed between the source version and the target version.

**Comment by takezoe** [comment] 2020-10-17 19:25
I confirmed that the current version of AmaterasUML doesn't work with JDK11 and upgrading XStream is necessary to support JDK11. I hope that https://github.com/takezoe/amateras-modeler/pull/13 will make AmaterasUML JDK11 compatible.

**Comment by takezoe** [comment] 2020-10-17 19:43
@megid2 I deployed amateras-modeler 2.0.0.202010180432 to the update site (http://takezoe.github.io/amateras-update-site). Could you try this version?

**Comment by megid2** [comment] 2020-10-18 19:13
Hi Naoki, thanks for the upgrade! I tried it for some Eclipse versions with JDK11:
https://takezoe.github.io/amateras-update-site/

eclipse 2019-03 works with JDK11, but warning on CLD file creation
eclipse 2020-06 works with JDK11, but warning on CLD file creation
eclipse 2020-09 works with JDK11, but warning on CLD file creation

All three versions print on the console:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.SerializationMembers (file:/home/kain/Desktop/eclipse-2019-03/configuration/org.eclipse.osgi/530/0/.cp/lib/xstream-1.4.13.jar) to method java.beans.PropertyChangeSupport.readObject(java.io.ObjectInputStream)
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.SerializationMembers
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations **will be denied in a future release**

The last line is particularly worrisome -- it seems that thoughtworks xstream is a bit brittle. Maybe using a more robust XML package could mitigate migration headaches in the future... Would you be interested? I would offer my help programming (though it could take a bit longer since I have young kids)

**Comment by takezoe** [comment] 2020-10-19 00:19
Can you open your diagrams even with that warning? If so, manual diagram files migration won't be necessary for now.

Since the current diagram serialization directly relies on XStream, it would be difficult to replace. I'm looking for a way to stop this warning. But if you have an idea to replace it with a migration solution, I would super appriciate it!

**Comment by megid2** [comment] 2020-10-19 18:02
Í can load SQD produced with AmaterasUML 1.3.2, but not CLD from the same version. And I see, replacing xstream may not be feasible without a lot of re-work.

Regarding migration, I found the culprit! "Visibility-1" becomes "Visibility$1" and so on. When I replace all occurences of "Visibility-" with "Visibility$", the CLDs load again.

One last question: In a class, the header has become quite big, with the package name displayed below the class name. Is there an option to get the old (more space-saving) kind of "package.Class" label back?

**Comment by takezoe** [comment] 2020-10-20 16:51
> Regarding migration, I found the culprit! "Visibility-1" becomes "Visibility$1" and so on. When I replace all occurences of "Visibility-" with "Visibility$", the CLDs load again.

That's good to know. I may be able to implement auto-conversion on AmaterasUML side.

> One last question: In a class, the header has become quite big, with the package name displayed below the class name. Is there an option to get the old (more space-saving) kind of "package.Class" label back?

I don't have a strong opinion about the presentation of the diagram. Let me compare the old version and the current version and will consider that idea :-)

**Closed** 2020-10-25 04:03 UTC

**Comment by megid2** [comment] 2020-10-28 07:56
Hi, did you, by any chance, have time to think the "package.Classname" labeling over?

**Comment by takezoe** [comment] 2020-10-29 11:36
Sorry, I didn't have time to consider it recently. Raising new issue for it might be better.
